### ISSUE TITLE
not working on safari /IoS

### ISSUE THREAD

**Issue by macbroadcast** [pubnub/paper-chat#4]
hey @girliemac ,
i really love this chat and polymer in general, i am using chrome mostly and firefox on ubuntu and never had a problem, but today i asked a friend on safari (IoS) to open up the page and was totally disapointed when i saw a blank white page, is this just a polymer 0.5 issue or with safari (mobile ) in general ?

Thanks

**Comment by stephenlb** [comment]
Likely Polymer 0.5 issue indeed!

**Comment by macbroadcast** [comment]
I got it working on safari (IOS), 
http://stackoverflow.com/questions/26479314/polymer-elements-not-rendered-on-safari-7-0
you need to add this script with polyemer 0.5 : script src="bower_components/platform/platform.js"></script

**Comment by stephenlb** [comment]
:+1:
