### ISSUE TITLE
Demo page is 404

### ISSUE THREAD

**Issue by tamakiii** [pubnub/paper-chat#6]
- README.md < `Try this on multiple browsers including mobile`
  - http://pubnub.github.io/paper-chat/index.html -> 404

**Comment by girliemac** [comment]
my bad. I changed the repo name to differentiate with the 1.x-compatible demo (still in private), but I changed it back so it should work soon. (it takes a while, so I close this issue once I confirmed!)

**Comment by tamakiii** [comment]
<3
